# Generated by Django 5.1.1 on 2024-11-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0, help_text='Enter course duration in hours'),
        ),
    ]
