# Generated by Django 5.1.1 on 2024-11-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_type',
            field=models.CharField(choices=[('months', 'Months'), ('years', 'Years')], default='hours', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
